# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 14) do

  create_table "feed_sources", :force => true do |t|
    t.column "url",     :string
    t.column "title",   :string
    t.column "user_id", :integer
  end

  create_table "notebooks", :force => true do |t|
    t.column "url",        :string
    t.column "content",    :string
    t.column "created_at", :datetime
  end

  create_table "read_logs", :force => true do |t|
    t.column "url",        :string
    t.column "created_at", :datetime
    t.column "user_id",    :integer
  end

  create_table "svlwords", :force => true do |t|
    t.column "word",       :string
    t.column "level",      :integer
    t.column "definition", :string
  end

  create_table "unknown_words", :force => true do |t|
    t.column "word",       :string
    t.column "url",        :string
    t.column "created_at", :datetime
    t.column "user_id",    :integer
  end

  create_table "users", :force => true do |t|
    t.column "login",           :string,   :limit => 80, :default => "", :null => false
    t.column "salted_password", :string,   :limit => 40, :default => "", :null => false
    t.column "email",           :string,   :limit => 60, :default => "", :null => false
    t.column "firstname",       :string,   :limit => 40
    t.column "lastname",        :string,   :limit => 40
    t.column "salt",            :string,   :limit => 40, :default => "", :null => false
    t.column "verified",        :integer,                :default => 0
    t.column "role",            :string,   :limit => 40
    t.column "security_token",  :string,   :limit => 40
    t.column "token_expiry",    :datetime
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
    t.column "logged_in_at",    :datetime
    t.column "deleted",         :integer,                :default => 0
    t.column "delete_after",    :datetime
  end

  create_table "vocabularies", :force => true do |t|
    t.column "word",       :string
    t.column "difficulty", :integer
    t.column "memlevel",   :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "stared",     :boolean
  end

  create_table "word_histories", :force => true do |t|
    t.column "word",       :string
    t.column "count",      :integer,  :default => 1
    t.column "user_id",    :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "word_variations", :force => true do |t|
    t.column "svlword_id", :integer
    t.column "form",       :string
  end

end
